NAIVE BAYES CLASSIFIER

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing
from sklearn.metrics import mean_squared_error,confusion_matrix,recall_score,precision_score

In [ ]:
data=pd.read_csv("/content/PlayTennis.csv")
X=data.iloc[:,:4]
y=data.iloc[:,-1]
print("the independent variables:\n",X)
print("\nthe dependent variable:\n",y)



the independent variables:
      Outlook Temperature Humidity    Wind
0      Sunny         Hot     High    Weak
1      Sunny         Hot     High  Strong
2   Overcast         Hot     High    Weak
3       Rain        Mild     High    Weak
4       Rain        Cool   Normal    Weak
5       Rain        Cool   Normal  Strong
6   Overcast        Cool   Normal  Strong
7      Sunny        Mild     High    Weak
8      Sunny        Cool   Normal    Weak
9       Rain        Mild   Normal    Weak
10     Sunny        Mild   Normal  Strong
11  Overcast        Mild     High  Strong
12  Overcast         Hot   Normal    Weak
13      Rain        Mild     High  Strong

the dependent variable:
 0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: Play Tennis, dtype: object


In [ ]:
le = preprocessing.LabelEncoder()
for i in range(4):
  X.iloc[:,i]=le.fit_transform(X.iloc[:,i])
y=le.fit_transform(y)

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1951: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[selected_item_labels] = value
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)


In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.3, random_state=0)
print("training dataset:\n",xtrain,"\n",ytrain)
print("\ntesting dataset:\n",xtest,"\n",ytest)

training dataset:
     Outlook  Temperature  Humidity  Wind
13        1            2         0     0
9         1            2         1     1
1         2            1         0     0
7         2            2         0     1
10        2            2         1     0
3         1            2         0     1
0         2            1         0     1
5         1            0         1     0
12        0            1         1     1 
 [0 1 0 0 1 1 0 0 1]

testing dataset:
     Outlook  Temperature  Humidity  Wind
8         2            0         1     1
6         0            0         1     0
4         1            0         1     1
11        0            2         0     0
2         0            1         0     1 
 [1 1 1 1 1]


In [ ]:
gaus= GaussianNB()
model= gaus.fit(xtrain, ytrain)
ypred=model.predict(xtest)
print("the predicted y values: ",ypred)
print("the test y values: ",ytest)
print("the  root mean squared error of the dataset is: ",mean_squared_error(ytest,ypred,squared=False))
mat=confusion_matrix(ytest,ypred)
print("the confusion matrix is:\n",mat)

the predicted y values:  [0 0 0 1 1]
the test y values:  [1 1 1 1 1]
the  root mean squared error of the dataset is:  0.7745966692414834
the confusion matrix is:
 [[0 0]
 [3 2]]


In [ ]:
print("the score for the training data set is: ",model.score(xtest,ytest))
print("the recall score: ",recall_score(ytest,ypred))
print("the precision score: ",precision_score(ytest,ypred))
sensitivity = mat[1,1]/(mat[0,0]+mat[1,1])
specificity = mat[1,0]/(mat[1,0]+mat[0,1])
print("specificity: ",specificity)
print("sensitivity: ",sensitivity)

the score for the training data set is:  0.4
the recall score:  0.4
the precision score:  1.0
specificity:  1.0
sensitivity:  1.0
